import { useState } from "react";
import { getClassificationLabel } from "../utils/evidence";

/**
 * EvidenceCard.jsx
 * ===================
 * One expandable card per retrieved evidence item, letting the user
 * "inspect exactly where the answer came from" — the explicit design
 * goal for this component. Every field shown comes directly from the
 * backend's EvidenceCitation object; nothing here is computed,
 * inferred, or constructed by the frontend.
 *
 * WHY source_url IS RENDERED AS-IS, NEVER BUILT HERE
 * -------------------------------------------------------
 * The link always points at `evidence.source_url`, exactly as the
 * backend returned it (which itself traces back to Phase 3's DailyMed
 * integration and Phase 4's SQLite storage). This component never
 * concatenates a setid, builds a DailyMed URL pattern, or otherwise
 * constructs a link itself — per the explicit project requirement that
 * source links must come from the backend, never be assembled in
 * React or generated by the LLM.
 */
export default function EvidenceCard({ evidence }) {
  const [expanded, setExpanded] = useState(false);
  const panelId = `evidence-panel-${evidence.evidence_id}`;

  return (
    <div className="evidence-card">
      <button
        type="button"
        className="evidence-card-header"
        aria-expanded={expanded}
        aria-controls={panelId}
        onClick={() => setExpanded((v) => !v)}
      >
        <span className="evidence-id">{evidence.evidence_id}</span>
        <span className="evidence-classification">{getClassificationLabel(evidence.classification)}</span>
        {evidence.drug_name && <span className="evidence-drug">{evidence.drug_name}</span>}
        <span className="chevron" aria-hidden="true">
          {expanded ? "\u25B2" : "\u25BC"}
        </span>
      </button>

      {expanded && (
        <div id={panelId} className="evidence-card-body">
          {evidence.section_name && (
            <p>
              <strong>Section:</strong> {evidence.section_name}
            </p>
          )}
          {evidence.manufacturer && (
            <p>
              <strong>Manufacturer:</strong> {evidence.manufacturer}
            </p>
          )}
          <p className="evidence-text">{evidence.text}</p>
          {evidence.source_url && (
            <p>
              <a href={evidence.source_url} target="_blank" rel="noopener noreferrer">
                View original source label
              </a>
            </p>
          )}
        </div>
      )}
    </div>
  );
}
